version: '3.4'

services:
  db:
   image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
   environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: 624545123Qw@
       MSSQL_PID: Developer
   volumes:
        - D:\docker-volume/my-data:/var/opt/mssql/data
   ports:
        - "1433:1433"

  web:
    image: "tope4949/retailposapi:v3"
    depends_on:
        - db
    environment:
            ServerName: "192.168.56.1"
            Database: "RetailPosApiDB"
            UserName: "sa"
            Password: "624545123Qw@"
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: https://*:5001;http://*:5000
            ASPNETCORE_HTTPS_PORT: 5001
            ASPNETCORE_Kestrel__Certificates__Default__Password: madison
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/dev_cert.pfx
    volumes: 
        - ./conf.d/https/:/https/
        - D:\docker-volume\my-img:/app/wwwroot/uploads
    ports:
          - 5000:5000
          - 5001:5001
volumes:
    my-data:
    my-img:
